### ISSUE TITLE
License Info

### ISSUE THREAD

**Issue by nykc** [NaturalHistoryMuseum/ckanext-userdatasets#6]
Maybe it's not related with any technical aspect of this extension... but it's very important to me (and probably for another githubers): which license applies to this awesome extension? Can't find any information. Could you update it?

**Comment by jrdh** [comment]
Hi @nykc, thanks! And yes, we do need to add licensing to this and our other extensions that are missing licenses too - thanks for the reminder! We are discussing this right now so I'll hopefully have an answer for you in the not too distant future!

**Comment by jrdh** [comment]
A license has been added, apologies for the delay!
